name: Newman API Tests
on: 
  workflow_dispatch:
jobs: 
  test: 
    defaults: 
      run: 
        working-directory: ./tests
    environment: staging
    name: "Run tests"
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        uses: actions/setup-node@v2
        with: 
          node-version: "18"
      - 
        name: "Install newman"
        run: "npm install -g newman"
      - 
        name: "Run tests"
        run: "newman run Personal.postman_collection.json -e reqres.postman_environment.json"
      - 
        name: "Upload HTML report"
        uses: actions/upload-artifact@v2
        with: 
          name: newman-report
          path: htmlreport.html
        
    